name: ractor
description: A fresh and funny state management package.
version: 1.1.2
homepage: https://github.com/huangbinjie/ractor.dart
author: corol <akira.binjie@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dart_actor: ^0.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  flutter_test:
    sdk: flutter