name: ractor
description: A fresh and funny state management package.
version: 0.0.1
homepage: https://github.com/huangbinjie/ractor.dart
author: corol <akira.binjie@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  dart_actor: ^0.0.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
