name: ractor_hooks
description: Reacr hooks style for ractor.
version: 0.0.6
homepage: https://github.com/huangbinjie/ractor.dart
author: corol <akira.binjie@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ractor: ^0.0.3
  flutter_hooks2: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
